version: "3.9"
services:
  db:
    container_name: coffee_db
    image: postgres:13
    restart: always
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 1234:5432
  node-apollo-gql-example:
    working_dir: /app/node-apollo-api
    restart: always
    build:
      context: .
    volumes:
      - .:/app:delegated
    command: yarn start
    ports:
      - 4000:4000

volumes:
  db: